name: ELIOS Autocode

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - "scripts/autocode.js"
      - "scripts/scripts/clés/**"      # tes clés actuelles
      - "scripts/scripts/cles/**"      # variante sans accent
      - "clés/**"                      # si un jour tu déplaces

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Générer un fichier
        run: node scripts/autocode.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit & push
        run: |
          git config user.name "elios-bot"
          git config user.email "elios-bot@users.noreply.github.com"
          git add generated/
          git commit -m "ELIOS: autocode" || echo "rien à committer"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
